[phases.setup]
nixPkgs = ["nodejs-18_x", "nodejs-18_x.pkgs.npm"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build --workspace=apps/ws-server"]

[start]
cmd = "cd apps/ws-server && node dist/index.js" 