[build]
builder = "nixpacks"

# Railway will use the build-app command from the nixpacks.toml file which 
# properly handles building packages first and then the app

[deploy]
restartPolicyType = "on_failure"

# Explicitly tell Nixpacks to use Node.js version 18 for the build environment.
# This should prevent it from trying to install or use any other Node.js version.
[env]
NIXPACKS_NODE_VERSION = "18"

# You can set APP_NAME in the Railway service settings
# Additional environment variables should be set here in Railway dashboard

# The [nixpacks] table in railway.toml for nodejs_version is an alternative
# but setting NIXPACKS_NODE_VERSION as an environment variable is often more direct.
# Ensure any older railway.toml [nixpacks] table for nodejs_version is removed or commented out.

# [nixpacks] # This section in railway.toml is often not needed if nixpacks.toml exists
# nodejs_version = "18" # Nixpacks usually infers this or can be set in nixpacks.toml too 